### ISSUE TITLE
Update to new Azure Storage client library

### ISSUE THREAD

**Issue by idg10** [ais-dotnet/Ais.Net.Receiver#80]
The library currently in use has now been marked as deprecated. Microsoft wants everyone to move over to the new `Azure.*` libraries.

**Comment by HowardvanRooijen** [comment]
I'll get on that, as I'd like to set up this on a raspberry PI so we can build more test datasets.

**Comment by HowardvanRooijen** [comment]
Fixed with 097802c33919e23d24841875d2db55ad16e855ba
